### ISSUE TITLE
Add license header fails

### ISSUE THREAD

**Issue by janvonrickenbach** [ansys/pre-commit-hooks#129]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

The pre-commit hook fails with following error (since about 2 weeks)

Traceback (most recent call last):
  File "/home/runner/.cache/pre-commit/repowatfqx5n/py_env-python3.9/bin/add-license-headers", line 8, in <module>
    sys.exit(main())
  File "/home/runner/.cache/pre-commit/repowatfqx5n/py_env-python3.9/lib/python3.9/site-packages/ansys/pre_commit_hooks/add_license_headers.py", line 558, in main
    return find_files_missing_header()
  File "/home/runner/.cache/pre-commit/repowatfqx5n/py_env-python3.9/lib/python3.9/site-packages/ansys/pre_commit_hooks/add_license_headers.py", line 533, in find_files_missing_header
    header.add_arguments(parser)
AttributeError: module 'reuse.header' has no attribute 'add_arguments'

See for example this run:

https://github.com/ansys/pydpf-composites/actions/runs/7563378347/job/20595676099

### 📝 Steps to reproduce

See above

### 💻 Which operating system are you using?

Windows

### 📀 Which ANSYS version are you using?

-

### 🐍 Which Python version are you using?

3.9

### 📦 Installed packages

```shell
CI/CD run
```

**Comment by RobPasMue** [comment]
Breaking change caused by major release of ``reuse``. Version 0.2.8 contains the fix for it. Opened https://github.com/ansys/pydpf-composites/pull/414 to solve the issue
