### ISSUE TITLE
add-license-headers bug with running hook in venv

### ISSUE THREAD

**Issue by klmcadams** [ansys/pre-commit-hooks#156]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

When you run the hook on Ubuntu in a virtual environment, the lint tool from reuse picks up the licenses of the .venv files, which are different than the default_license.

https://github.com/ansys/grantami-bomanalytics/actions/runs/8561534493/job/23462939759#step:2:488

Traceback (most recent call last):
  File "/home/runner/.cache/pre-commit/repoujitykj9/py_env-python3.10/bin/add-license-headers", line 8, in <module>
    sys.exit(main())
  File "/home/runner/.cache/pre-commit/repoujitykj9/py_env-python3.10/lib/python3.10/site-packages/ansys/pre_commit_hooks/add_license_headers.py", line 566, in main
    return find_files_missing_header()
  File "/home/runner/.cache/pre-commit/repoujitykj9/py_env-python3.10/lib/python3.10/site-packages/ansys/pre_commit_hooks/add_license_headers.py", line 550, in find_files_missing_header
    missing_headers = list(list_noncompliant_files(args, proj))
  File "/home/runner/.cache/pre-commit/repoujitykj9/py_env-python3.10/lib/python3.10/site-packages/ansys/pre_commit_hooks/add_license_headers.py", line 205, in list_noncompliant_files
    lint_json["non_compliant"]["missing_licenses"][args.custom_license]
KeyError: 'MIT'

### 📝 Steps to reproduce

1. Create a virtual env on a Linux system (or WSL Ubuntu)
2. `pre-commit run --all-files`

There will be an error message. Open add-license-headers.py file using `vi` provided the path in the error output, add a print statement above line 206 `print(lint_json["non_compliant"]["missing_licenses"])` & you'll see a different license as the key with a list of .venv files. 

To fix this, add a try/except or ignore for hidden directories, or figure out if there's a way to get reuse's lint tool to ignore hidden directories

### 💻 Which operating system are you using?

Linux

### 📀 Which ANSYS version are you using?

N/A

### 🐍 Which Python version are you using?

3.9

### 📦 Installed packages

```shell
N/A
```

**Comment by klmcadams** [comment]
Closed by #163
