### ISSUE TITLE
add-license-headers requires 'developer mode' on Windows 10

### ISSUE THREAD

**Issue by james-packer** [ansys/pre-commit-hooks#250]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

The add-licence-headers pre-commit hook uses symlinks (see https://github.com/ansys/pre-commit-hooks/blob/d837b5a5a05e8a236949b96ae849f669fe3f69d2/src/ansys/pre_commit_hooks/add_license_headers.py#L167). On Windows 10, unless the user has enabled 'developer mode', this requires elevated permissions, so the user has to run the git commit command as an administrator. The workaround for this is to enable developer mode: https://blogs.windows.com/windowsdeveloper/2016/12/02/symlinks-windows-10/

### 📝 Steps to reproduce

Run pre-commit hooks on windows 10 without developer mode enabled. 
A traceback similar to the following will be generated:
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\jpacker\.cache\pre-commit\repoq9up3tzk\py_env-python3.11\Scripts\add-license-headers.EXE\__main__.py", line 7, in <module>
  File "C:\Users\jpacker\.cache\pre-commit\repoq9up3tzk\py_env-python3.11\Lib\site-packages\ansys\pre_commit_hooks\add_license_headers.py", line 736, in main
    return find_files_missing_header()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jpacker\.cache\pre-commit\repoq9up3tzk\py_env-python3.11\Lib\site-packages\ansys\pre_commit_hooks\add_license_headers.py", line 707, in find_files_missing_header
    link_assets(assets, os_git_root, args)
  File "C:\Users\jpacker\.cache\pre-commit\repoq9up3tzk\py_env-python3.11\Lib\site-packages\ansys\pre_commit_hooks\add_license_headers.py", line 133, in link_assets
    mkdirs_and_link(value["path"], hook_asset_dir, repo_asset_dir, value["default_file"])
  File "C:\Users\jpacker\.cache\pre-commit\repoq9up3tzk\py_env-python3.11\Lib\site-packages\ansys\pre_commit_hooks\add_license_headers.py", line 167, in mkdirs_and_link
    os.symlink(src, dest)
**OSError: [WinError 1314] A required privilege is not held by the client:** 'C:\\Users\\jpacker\\.cache\\pre-commit\\repoq9up3tzk\\py_env-python3.11\\Lib\\site-packages\\ansys\\pre_commit_hooks\\assets\\.reuse\\templates\\ansys.jinja2' -> 'C:\\Workspace\\pymotorcad\\.reuse\\templates\\ansys.jinja2'

### 💻 Which operating system are you using?

Windows

### 📀 Which ANSYS version are you using?

PyMotorCAD with Motor-CAD 2024.2 and 2025.1.0.5 (testing)

### 🐍 Which Python version are you using?

3.9

### 📦 Installed packages

```shell
accessible-pygments==0.0.5
alabaster==1.0.0
ansys-api-platform-instancemanagement==1.1.0
-e git+https://github.com/ansys/pymotorcad@3f69c7c4fdd5c27408ed9874a1cb7181b32d787b#egg=ansys_motorcad_core
ansys-platform-instancemanagement==1.1.2
ansys-sphinx-theme==1.1.2
babel==2.16.0
beautifulsoup4==4.12.3
bezier==2024.6.20
cachetools==5.5.0
certifi==2024.8.30
cfgv==3.4.0
chardet==5.2.0
charset-normalizer==3.4.0
colorama==0.4.6
contourpy==1.3.0
coverage==7.6.2
cycler==0.12.1
distlib==0.3.9
docutils==0.21.2
filelock==3.16.1
fonttools==4.54.1
grpcio==1.66.2
identify==2.6.1
idna==3.10
imagesize==1.4.1
importlib_metadata==8.5.0
iniconfig==2.0.0
Jinja2==3.1.4
kiwisolver==1.4.7
MarkupSafe==3.0.1
matplotlib==3.9.2
networkx==3.4
nodeenv==1.9.1
numpy==2.1.2
numpydoc==1.8.0
packaging==24.1
pdf2image==1.17.0
pillow==10.4.0
platformdirs==4.3.6
pluggy==1.5.0
pre_commit==4.0.1
protobuf==5.28.2
psutil==6.0.0
pydata-sphinx-theme==0.15.4
Pygments==2.18.0
pypandoc==1.13
pyparsing==3.1.4
pyproject-api==1.8.0
pytest==8.3.3
pytest-cov==5.0.0
python-dateutil==2.9.0.post0
PyYAML==6.0.2
requests==2.32.3
scipy==1.14.1
six==1.16.0
snowballstemmer==2.2.0
soupsieve==2.6
Sphinx==8.0.2
sphinx-copybutton==0.5.2
sphinx-gallery==0.17.1
sphinxcontrib-applehelp==2.0.0
sphinxcontrib-devhelp==2.0.0
sphinxcontrib-htmlhelp==2.1.0
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==2.0.0
sphinxcontrib-serializinghtml==2.0.0
tabulate==0.9.0
tox==4.21.2
typing_extensions==4.12.2
urllib3==2.2.3
virtualenv==20.26.6
zipp==3.20.2
```

**Comment by klmcadams** [comment]
Closed by #420
